### ISSUE TITLE
`fatal: could not read Username for 'https://github.com': No such device or address`

### ISSUE THREAD

**Issue by paw-lu** [OleksiyRudenko/gha-git-credentials#6]
Trying to use this action to authenticate git so it can push to main on a remote branch:

```yml
      - name: Setup git
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          global: true
          name: Tester testy
          email: tester@testit.com
          actor: paw-lu

      - name: Commit
        working-directory: ./Dash-User-Contributions
        run: |
          git add --all
          git commit --message="Change!"

      - name: Push
        working-directory: ./Dash-User-Contributions
        run: |
          git push --set-upstream origin ${{ github.run_id }}-${{ github.run_attempt }}

```
But on step `Push` I get [`fatal: could not read Username for 'https://github.com': No such device or address`](https://github.com/paw-lu/test-gh-actions/actions/runs/3294619216/jobs/5432316809#step:8:7)

[Example repo has been set up to provide a minimal example](https://github.com/paw-lu/test-gh-actions/blob/75de3623b91773c2dc0a3da091913b1fc695edbb/.github/workflows/release.yml).

---

Thanks for the action!
